/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'root' at '7/29/15 10:27 AM' with Gradle 2.5-rc-2
 *
 * @author root, @date 7/29/15 10:27 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
